### ISSUE TITLE
Nested data not supported

### ISSUE THREAD

**Issue by zkamvar** [gadenbuie/quarto-partials#5]
I would like to create a page with profile cards with data that looks something like this:

```yaml
ppl:
  hickory:
    name: "Doc"
    links:
      - name: homepage
        url: https://example.com/home
      - name: awaypage
        url: https://example.com/away
```

If I have a partial that looks like this:

```markdown
Name: {{ name }}

{{#links}}
  <a href={{.url}}>{{.name}}</a>
{{/links}}
```

and I call it like `{{< partial _partial.qmd ppl.hickory >}}`

I get the name but the links do not work. I found the problem is due to the `pandoc_stringify()` function taking the list of links and concatenating them.
